stages:
  download_data:
    cmd: python src/data/download_data.py
    deps:
      - src/data/download_data.py
    outs:
      - data/raw

  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw
    params:
      - data.test_size
      - data.random_state
    outs:
      - data/processed

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed
    params:
      - model
    metrics:
      - metrics/metrics.json:
          cache: false
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/models/evaluate.py
    deps:
      - src/models/evaluate.py
      - models/model.pkl
      - data/processed
    metrics:
      - metrics/evaluation.json:
          cache: false
    plots:
      - metrics/plots